### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by Korri** [andheiberg/laravel-image#2]
There is a mistake in the doc:

`Add 'Image' => \Image\Facades\Image', to aliases in app/config/app.php`

Shoud be:

`Add 'Image' => 'Andheiberg\Image\Facades\Image', to aliases in app/config/app.php`

**Comment by andheiberg** [comment]
Could you please make a pull request?

**Comment by andheiberg** [comment]
Fixed in latest commit
