### ISSUE TITLE
on the fly manipulation

### ISSUE THREAD

**Issue by iwyg** [andheiberg/laravel-image#3]
Hi, just read about this repo on creativepunch. I don't want to hijack this repo, just letting you know that there's a laravel package that does exactly that (so maybe of interest for you). 

https://github.com/iwyg/jitimage

Contributions are highly welcome :)

Best, iwyg

**Comment by andheiberg** [comment]
Well that would mean there are two :) 

My package is fully functional and does everything I need to do.

From reading your readme you definetly do something's I don't, but as far as I can see your caching layer does not support other filesystems which is one of the features I need. 

Thanks for reaching out though.

**Comment by iwyg** [comment]
In deed. However, remote sources are supported. 
Swapping the filesystem to 'frenkynet/flysystem' is a thing I've already considered. 

Does laravel-image handle http caching?

Thanks for the heads up.

**Comment by andheiberg** [comment]
What do you mean with http caching?

The files have absolute urls if that is what you mean, so php is not run when downloading an image.

**Comment by iwyg** [comment]
Ah, I see. You require the processed images to be cached on a public directory.

**Comment by andheiberg** [comment]
Yeah, thats the way to go in my opinion. Do you do it differently?
