### ISSUE TITLE
Cannot install: frenkynet/flysystem not found

### ISSUE THREAD

**Issue by ejunker** [andheiberg/laravel-image#4]
I want to install the 1.0.2 version so I did:
`composer require andheiberg/image:1.0.2`

I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for andheiberg/image 1.0.2 -> satisfiable by andheiberg/image[1.0.2].
    - andheiberg/image 1.0.2 requires frenkynet/flysystem 0.1.* -> no matching package found.
```

It looks like `frenkynet/flysystem` is now named `league/flysystem`

**Comment by andheiberg** [comment]
Yeah I haven't been active on a project that uses this for a while...

Basically flysystem was accepted by phpleague which is awesome, but it sorta means we have to update dependencies. So yes we could use league, but if my memory serves me that does not include laravel facade and service provider. So the right cause of action would be to change it to graham-campbell/flysystem.

I will look in to that now.

**Comment by andheiberg** [comment]
Actually you are right... for this particular use case I don't need a facade or a service provider.

I've added a 1.1 branch and a 1.1.0 version in order to not bother my old projects :) you should be able to use that version successfully.

Thanks :)

**Comment by ejunker** [comment]
Thanks for resolving this so quickly! Just to let you know, league/flysystem requires PHP 5.4 or higher so now your package requires PHP 5.4 or higher. The server I'm using doesn't have PHP 5.4 but hopefully it can be upgraded soon. :smile:

**Comment by andheiberg** [comment]
Thanks so much :)

Glad that the package is helping someone besides the couple of projects I use it for.
